ext {
<<<<<<<< HEAD:src/zh/cartoonmad/build.gradle
    extName = 'CartoonMad'
    extClass = '.CartoonMad'
    extVersionCode = 1
========
    extName = 'COMIC FUZ'
    extClass = '.ComicFuz'
    extVersionCode = 2
>>>>>>>> upstream/main:src/ja/comicfuz/build.gradle
    isNsfw = true
}

apply from: "$rootDir/common.gradle"
